spring.datasource.url=jdbc:h2:mem:store
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.profiles.active=dev
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:manufacturer.sql, classpath:client.sql, classpath:employee.sql, classpath:appliance.sql

spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

logging.level.org.springframework.context.support=DEBUG

jwtSecret=Jhsij86hHgj97Jhiu8899xcJhkskciscsksxkJHkHfjJbjGJKhJhsij86hHgj97Jhiu8899xcJhkskciscsksxkJHkHfjJbjGJKh
app.jwtSecret=Jhsij86hHgj97Jhiu8899xcJhkskciscsksxkJHkHfjJbjGJKhJhsij86hHgj97Jhiu8899xcJhkskciscsksxkJHkHfjJbjGJKh